-- 재고 서비스의 테이블. specs/001-place-order/data-model.md 3절을 그대로 옮겼다.
-- 이미 적용된 마이그레이션 파일은 고치지 않고, 바꿀 것이 생기면 새 파일을 더한다.

CREATE TABLE STOCK (
    PRODUCT_ID VARCHAR2(20) NOT NULL,
    QUANTITY   NUMBER(10)   NOT NULL,
    CONSTRAINT PK_STOCK PRIMARY KEY (PRODUCT_ID),
    -- 수량을 줄이는 코드에 실수가 있어도 음수가 저장되지 않게 하는 마지막 방어선이다.
    CONSTRAINT CK_STOCK_QTY CHECK (QUANTITY >= 0)
);

CREATE TABLE RESERVATIONS (
    ORDER_NO   NUMBER(19)   NOT NULL,
    STATUS     VARCHAR2(20) NOT NULL,
    REASON     VARCHAR2(30),
    CREATED_AT TIMESTAMP    NOT NULL,
    UPDATED_AT TIMESTAMP    NOT NULL,
    -- 같은 주문 번호의 예약은 한 줄뿐이다. 같은 번호가 동시에 들어와도 한쪽만 들어간다.
    CONSTRAINT PK_RESERVATIONS PRIMARY KEY (ORDER_NO),
    CONSTRAINT CK_RESERVATIONS_STATUS CHECK (STATUS IN ('RESERVED', 'REJECTED', 'RELEASED')),
    CONSTRAINT CK_RESERVATIONS_REASON CHECK (REASON IS NULL OR REASON IN ('OUT_OF_STOCK', 'PRODUCT_NOT_FOUND'))
);

-- STOCK으로 가는 외래 키는 두지 않는다. 재고 데이터에 없는 상품의 줄도 남겨야 하기 때문이다.
CREATE TABLE RESERVATION_ITEMS (
    ORDER_NO   NUMBER(19)   NOT NULL,
    PRODUCT_ID VARCHAR2(20) NOT NULL,
    QUANTITY   NUMBER(2)    NOT NULL,
    RESULT     VARCHAR2(20),
    CONSTRAINT PK_RESERVATION_ITEMS PRIMARY KEY (ORDER_NO, PRODUCT_ID),
    CONSTRAINT FK_RESERVATION_ITEMS_RES FOREIGN KEY (ORDER_NO) REFERENCES RESERVATIONS (ORDER_NO)
);
