-- 로컬 실행과 E2E 테스트가 쓰는 초기 재고. 상품 P-001부터 P-005까지 각 100개다.
-- 서비스 통합 테스트와 Mapper 테스트는 이 행을 쓰지 않고, 테스트 케이스의 상품 ID(A, B, Z)를 직접 넣고 지운다.

INSERT INTO STOCK (PRODUCT_ID, QUANTITY) VALUES ('P-001', 100);
INSERT INTO STOCK (PRODUCT_ID, QUANTITY) VALUES ('P-002', 100);
INSERT INTO STOCK (PRODUCT_ID, QUANTITY) VALUES ('P-003', 100);
INSERT INTO STOCK (PRODUCT_ID, QUANTITY) VALUES ('P-004', 100);
INSERT INTO STOCK (PRODUCT_ID, QUANTITY) VALUES ('P-005', 100);
